### ISSUE TITLE
difficulty following installation instruction

### ISSUE THREAD

**Issue by rlzijdeman** [RinkeHoekstra/qber#1]
Hi, I've tried to install qber, but run into the following issues:

In the readme, after the gitclone part it reads: "Change directory to directory and ". It appears there's something missing in that line (At first I switched to a new directory to create the virtualenv, but I noticed that later on you need to be in the git directory for the requirements install to work)?

Then I installed virtualenv and typed `virtualenv .` and after it finished, I typed: `source bin/activate` and after that changed back to the git directory and typed: `pip install -r requirements.txt`.

It then starts collecting and downloading a bunch of stuff, but halts at: 

```
Collecting savReaderWriter==3.3.0 (from -r requirements.txt (line 13))
  Could not find any downloads that satisfy the requirement savReaderWriter==3.3.0 (from -r     requirements.txt (line 13))
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-    external savReaderWriter to allow).
  No distributions at all found for savReaderWriter==3.3.0 (from -r requirements.txt (line 13))
```

Any suggestions on the 'directory'-line and how I can fix the savReaderWriter issue?

**Comment by rlzijdeman** [comment]
Hi, I've tried to look a bit more into this. When I comment out the saveReaderWriter file the requirements.txt runs fine. So I figured that the problem lies in how I install savReaderWriter. Do you still remember how you did that? I've looked into the documentation at http://pythonhosted.org//savReaderWriter/ and there's a special section for mac osx users, but I'm not sure how to implement what's being asked there:

```
"Note Users of Mac OS X need to do two additional things:
DYLD_LIBRARY_PATH needs to be set to the directory where the SPSS I/O libraries for Mac OS X live. You may also want to edit your ~/.bashrc accordingly.
ioLocale needs to be set manually (work-around). The ioLocale is the locale of the SPSS I/O, which is  supposed to be copied from the host system, if unset (i.e., equal to None). However, Python locale.setlocale and locale.getlocale are quirky in Mac OS X (see also this OS X and Python locale snippet)."
```

**Comment by RinkeHoekstra** [comment]
Indeed the savReaderWriter installation is a bit tricky.
- install with `pip -r requirements.txt --allow-external`
- download the libraries linked to from the savReaderWriter homepage
- set the `DYLD_LIBRARY_PATH` to the location of the libraries (e.g. on unix-like systems `export DYLD_LIBRARY_PATH="/path/to/the/libraries/"`)
- The `ioLocale` is set in the call to the reader (or writer).... see the code

I will update the documentation in a later release.

**Comment by rlzijdeman** [comment]
Hi, thanks for this pointer. I've installed with:
`pip install -r requirements.txt --allow-external savReaderWriter`
and then followed your other pointers. 

If I then run `python run.py`, qber starts and directs me to a local address. However, if I load that address in my browser, I see a header "Clariah QBer", but nothing else. In the term, a load of stuff is being reported, but it halts at: `OSError: dlopen(/Users/xxx/git/lib/python2.7/site-packages/savReaderWriter/spssio/macos/libicuuc48.1.dylib, 6): Library not loaded: @executable_path/../lib/libicudata48.1.dylib
  Referenced from: /Users/xxx/git/lib/python2.7/site-packages/savReaderWriter/spssio/macos/libicuuc48.1.dylib
  Reason: image not found`.

**Comment by RinkeHoekstra** [comment]
Moved to pandas
