### ISSUE TITLE
'Upload CSV' button

### ISSUE THREAD

**Issue by albertmeronyo** [RinkeHoekstra/qber#61]
In the welcome screen, users should be able to upload their own curated CSV files to the hub.

Related to CLARIAH/wp4-requirements#17

**Comment by RinkeHoekstra** [comment]
Agreed, but this is not entirely an issue of QBer, it should be supported by the API itself (as a tunnel to Gitlab)

**Comment by RinkeHoekstra** [comment]
There's a Dropbox chooser window that provides a URL, which can then be used to ask the datalegend API to provide a dataset description for that URL. The API will also make sure that the dataset is published on Gitlab with the proper email address & username (CLARIAH/wp4-datalegend-api#10)

NB: need to test how the resulting RDF will end up.

Closed with CLARIAH/wp4-requirements#17 and d51c635
