### ISSUE TITLE
'Download dump' button

### ISSUE THREAD

**Issue by albertmeronyo** [RinkeHoekstra/qber#62]
We should have a button to allow users to download their RDF, and the JSON of their mappings.

Related to CLARIAH/wp4-requirements#18

**Comment by RinkeHoekstra** [comment]
Well... cdd642b does add a button, but it doesn't really allow users to download their RDF now does it?

**Comment by albertmeronyo** [comment]
Yes, it does. Users need first to 'submit' since this is currently the only way of executing the converters. After this, the button gets enabled and the RDF can be downloaded (now the Navbar component is stateful). Test it yourself! --> http://qber-dev.clariah-sdh.eculture.labs.vu.nl/ (we'll need to add this to the OAuth sources btw)
